import '../styles/globals.css';
import { Inter } from 'next/font/google';

import Header from '../components/header/header';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<head>
				<meta charset='UTF-8' />

				<link
					rel='icon'
					type='image/png'
					sizes='32x32'
					href='./images/favicon-32x32.png'
				/>

				<title>Frontend Mentor | Bookmark landing page</title>
			</head>
			<body className={inter.className}>
				<Header />
				{children}
			</body>
			<footer>
				<p class='attribution'>
					Challenge by{' '}
					<a
						href='https://www.frontendmentor.io?ref=challenge'
						target='_blank'
					>
						Frontend Mentor
					</a>
					. Built by <a href='#'>Dean Jeffery</a>.
				</p>
			</footer>
		</html>
	);
}
